name: Build

on:
  push:
  pull_request:
  release:
    types: [created]
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-repository

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install -P deployment,frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish JARs
        uses: actions/upload-artifact@v2
        with:
          name: JARs
          path: target/*.jar

      - name: Publish designer (tar)
        uses: actions/upload-artifact@v2
        with:
          name: designer.tar
          path: dist/designer.tar

      - name: Publish designer (zip)
        uses: actions/upload-artifact@v2
        with:
          name: designer.zip
          path: dist/designer.zip

      - name: Notify slack
        if: always() && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && github.repository_owner == 'vlingo'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ci-cd
          SLACK_USERNAME: Bob the Builder
          SLACK_ICON: 'https://vlingo.io/wp-content/uploads/cropped-vlingo-favicon-180x180.png'
          SLACK_FOOTER: '${{ github.repository }}'

      - name: Cleanup
        run: rm -rf ~/.m2/repository/io/vlingo

  publish-designer:
    runs-on: ubuntu-latest
    name: Publish Designer
    needs: build
    if: github.event_name == 'release'
    steps:
      -   uses: actions/download-artifact@v1
          with:
            name: designer.tar
            path: .
      -   uses: actions/download-artifact@v1
          with:
            name: designer.zip
            path: .
      -   name: Upload designer.tar
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./designer.tar
            asset_name: designer.tar
            asset_content_type: application/x-tar
      -   name: Upload designer.zip
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./designer.zip
            asset_name: designer.zip
            asset_content_type: application/zip
